"""add classification columns

Revision ID: 4dd710d5531a
Revises: 91c4a4495a1b
Create Date: 2026-09-09 19:11:58.253884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd710d5531a'
down_revision: Union[str, Sequence[str], None] = '91c4a4495a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('category', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('company_stage', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('delivery_models', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('business_models', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'business_models')
    op.drop_column('companies', 'delivery_models')
    op.drop_column('companies', 'company_stage')
    op.drop_column('companies', 'category')
    # ### end Alembic commands ###
